---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/users":
    post:
      summary: Users register
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/user"
        description: JSON to create the user
  "/{locale}/v1/users/login":
    parameters:
    - name: locale
      in: path
      description: locale
      required: true
      schema:
        type: string
    post:
      summary: Users login
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/login_user"
        description: JSON to login
components:
  securitySchemes: {}
  schemas:
    user:
      type: object
      properties:
        email:
          type: string
          required: true
        password:
          type: string
          required: true
        age:
          type: integer
          required: true
        store_attributes:
          type: object
          properties:
            name:
              type: string
              required: true
      example:
        user:
          email: test@example.com
          password: '12345678'
          age: 31
          store_attributes:
            name: test
    login_user:
      type: object
      properties:
        email:
          type: string
          required: true
        password:
          type: string
          required: true
      example:
        user:
          email: test@example.com
          password: '12345678'
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000
