---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/categories":
    post:
      summary: Categories create
      tags:
      - Categories
      parameters: []
      security:
      - Bearer: []
      responses:
        '201':
          description: Successful
        '400':
          description: Bad Request
        '401':
          description: Not Authorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/category"
        description: JSON to create the category
    get:
      summary: Categories list
      tags:
      - Categories
      security:
      - Bearer: []
      responses:
        '200':
          description: Successful
        '401':
          description: Not Authorized
  "/v1/categories/{id}":
    delete:
      summary: Categories delete
      tags:
      - Categories
      parameters:
      - name: id
        in: path
        description: Category id
        schema:
          "$ref": "#/components/schemas/category_id"
        required: true
      security:
      - Bearer: []
      responses:
        '200':
          description: Successful
        '401':
          description: Not Authorized
        '404':
          description: Category Not Found
    put:
      summary: Categories update
      tags:
      - Categories
      parameters:
      - name: id
        in: path
        description: Category id
        schema:
          "$ref": "#/components/schemas/category_id"
        required: true
      security:
      - Bearer: []
      responses:
        '200':
          description: Successful
        '401':
          description: Not Authorized
        '404':
          description: Category Not Found
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/category"
        description: JSON to update the category
  "/v1/posts":
    post:
      summary: Posts create
      tags:
      - Posts
      parameters: []
      security:
      - Bearer: []
      responses:
        '201':
          description: Successful
        '401':
          description: Not Authorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/post"
        description: JSON to create the post
    get:
      summary: Posts list
      tags:
      - Posts
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
  "/v1/posts/{id}":
    delete:
      summary: Delete a post
      tags:
      - Posts
      parameters:
      - name: id
        in: path
        type: string
        description: Post id
        schema:
          "$ref": "#/components/schemas/post_id"
        required: true
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
    put:
      summary: Posts update
      tags:
      - Posts
      parameters:
      - name: id
        in: path
        description: Post id
        schema:
          "$ref": "#/components/schemas/post_id"
        required: true
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/post"
        description: JSON to update the post
  "/v1/posts/{post_id}/restore":
    post:
      summary: Restore a post
      tags:
      - Posts
      parameters:
      - name: post_id
        in: path
        type: string
        description: Post id
        schema:
          "$ref": "#/components/schemas/post_id"
        required: true
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
  "/v1/profiles/{id}":
    get:
      summary: Profiles show
      tags:
      - Profiles
      parameters:
      - name: id
        in: path
        description: profile id
        schema:
          "$ref": "#/components/schemas/profile_id"
        required: true
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
    put:
      summary: Profiles update
      tags:
      - Profiles
      parameters:
      - name: id
        in: path
        description: profile id
        schema:
          "$ref": "#/components/schemas/profile_id"
        required: true
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/profile"
        description: JSON to update the profile
  "/v1/skills":
    post:
      summary: Skill create
      tags:
      - Skills
      parameters: []
      security:
      - Bearer: []
      responses:
        '201':
          description: Successful
        '401':
          description: Not Authorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/skill"
        description: JSON to create skill
  "/v1/skills/{id}":
    delete:
      summary: Destroy skill
      tags:
      - Skills
      parameters:
      - name: id
        in: path
        description: Skill id
        schema:
          "$ref": "#/components/schemas/skill_id"
        required: true
      security:
      - Bearer: []
      responses:
        '200':
          description: Successful
        '401':
          description: Not Authorized
        '404':
          description: Not Found
    put:
      summary: Skill update
      tags:
      - Skills
      parameters:
      - name: id
        in: path
        description: Skill id
        schema:
          "$ref": "#/components/schemas/skill_id"
        required: true
      security:
      - Bearer: []
      responses:
        '200':
          description: Successful
        '401':
          description: Not Authorized
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/skill"
        description: JSON to update skill
  "/v1/users":
    post:
      summary: Users register
      tags:
      - Users
      parameters: []
      security:
      - Bearer: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/user"
        description: JSON to create the user
  "/{locale}/v1/users/login":
    parameters:
    - name: locale
      in: path
      description: locale
      required: true
      schema:
        type: string
    post:
      summary: Users login
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/login_user"
        description: JSON to login
components:
  securitySchemes:
    Bearer:
      description: Bearer token of the logged user to access the API ressources
      type: apiKey
      in: header
      name: Authorization
  schemas:
    user:
      type: object
      properties:
        email:
          type: string
          required: true
        password:
          type: string
          required: true
        age:
          type: integer
          required: true
        company_attributes:
          type: object
          properties:
            name:
              type: string
              required: true
      example:
        user:
          email: test@example.com
          password: '12345678'
          age: 31
          company_attributes:
            name: test
    login_user:
      type: object
      properties:
        email:
          type: string
          required: true
        password:
          type: string
          required: true
      example:
        user:
          email: raul@example.com
          password: 123abc
    post_id:
      type: integer
      required: true
      example: 1
    profile_id:
      type: integer
      required: true
      example: 1
    category_id:
      type: integer
      required: true
      example: 1
    skill_id:
      type: integer
      required: true
      example: 1
    post:
      type: object
      properties:
        title:
          type: string
          required: true
        content:
          type: string
          required: true
        image_url:
          type: string
          required: true
        credits:
          type: string
          required: false
      example:
        post:
          title: test
          content: post description
          image_url: image.url.com
          credits: "(page.link,page name,user name)"
    category:
      type: object
      properties:
        title:
          type: string
          required: true
        description:
          type: string
          required: true
        slug:
          type: string
          required: true
          unique: true
      example:
        title: Category title
        description: Category description
        slug: category-title
    skill:
      type: object
      properties:
        name:
          type: string
          required: true
        icon_url:
          type: string
          required: false
        level:
          type: integer
          required: false
        category_id:
          type: string
          required: true
      example:
        name: Skill name
        icon_url: image.url.com/icon
        level: 1
        category_id: 9
    profile:
      type: object
      properties:
        name:
          type: string
          required: false
        last_name:
          type: string
          required: false
        headliner:
          type: string
          required: false
        bio:
          type: text
          required: false
        city:
          type: string
          required: false
        state:
          type: string
          required: false
        country:
          type: string
          required: false
        phone_number:
          type: string
          required: false
        social_media:
          type: string
          required: false
        skills_attributes:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                required: true
              icon_url:
                type: string
                required: false
              level:
                type: integer
                required: false
              category_id:
                type: string
                required: true
              profile_id:
                type: string
                required: true
      example:
        profile:
          name: user name updated
          last_name: user last name updated
          headliner: user headliner updated
          bio: user bio updated
          city: city updated
          state: state updated
          country: country updated
          phone_number: phone number updated
          social_media: linkedin.com,facebook.com,instagram.com,github.com,whatsapp.com,x.com
          skills_attributes:
          - name: skill name updated
            icon_url: image.url.com/icon
            level: 1
            category_id: 9
            profile_id: 3
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000
